version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./public:/usr/src/app/public
    environment:
      NODE_ENV: development
